elastic/apm-aggregation

- aggregators/internal/hdrhistogram/hdrhistogram.go
- aggregators/internal/hdrhistogram/hdrhistogram_test.go
The PR improves bucket calculation for HDR histogram representation by utilizing the sparse representation we use. The buckets are calculated for only the buckets that are used for recording values and the allocations are also made accordingly.
> Use custom distribution logic

- aggregators/internal/hdrhistogram/hdrhistogram.go
- aggregators/internal/hdrhistogram/hdrhistogram_test.go
It is possible that histogram's `RecordValues` is called with a count of `0`. The below code handles the case by discarding such values from the `Buckets` calculation.
> Fix histogram handling of recording 0 count values

- aggregators/aggregator_test.go
- aggregators/codec_test.go
- BenchmarkAggregateBatch* should not harvest, for a more stable benchmark
- Rename BenchmarkAggregateBatch to BenchmarkAggregateBatchSerial
- Add BenchmarkAggregateBatchParallel
> bench: Modify BenchmarkAggregateBatch to not harvest and bench concurrency

- aggregators/aggregator_test.go
Attempts fixing a flaky test. The test waits for first harvest to be done, however, the aggregation interval and the wait time are both 1 second which causes flakiness.
> Increase time to wait for first harvest

- Makefile
- aggregationpb/aggregation_vtproto.pb.go
- aggregationpb/labels_vtproto.pb.go
- tools/go.mod
- tools/go.sum
See #16. Use vtproto fork to generate code that does not have the pooling bug.
The changes to vtproto: https://github.com/planetscale/vtprotobuf/compare/main...carsonip:vtprotobuf:fix-pooling
It fixes our case and generates the right code, but not sure if it breaks any code outside our use case.
benchstat:
```
goos: linux
goarch: amd64
│ bench-out/vtproto-fix-codegen-before │ bench-out/vtproto-fix-codegen-after │
│                sec/op                │    sec/op     vs base               │
AggregateCombinedMetrics-16                           3.537µ ±  3%    3.416µ ± 5%        ~ (p=0.240 n=6)
AggregateBatchSerial-16                               18.02µ ±  4%    17.55µ ± 3%   -2.60% …
```
> Use vtproto fork to fix pooling

- aggregators/aggregator.go
- aggregators/codec.go
- Reuse labels backing array to reduce allocs. Missed in #18 
- Remove tracing for AggregateBatch to reduce allocs
benchstat:
```
goos: linux
goarch: amd64
│ bench-out/optimizations3-before │   bench-out/optimizations3-after   │
│             sec/op              │   sec/op     vs base               │
AggregateCombinedMetrics-16                       3.318µ ± 4%   3.409µ ± 4%        ~ (p=0.258 n=6)
AggregateBatchSerial-16                           16.89µ ± 8%   13.57µ ± 5%  -19.65% (p=0.002 n=6)
AggregateBatchParallel-16                         18.13µ ± 4%   14.71µ ± 9%  -18.88% (p=0.002 n=6)
CombinedMetricsEncoding-16                        5.279µ ± 4%   5.276µ ± 4%        ~ (p=0.394 …
```
> Performance improvements

- aggregators/aggregator.go
- aggregators/aggregator_test.go
- aggregators/codec.go
- aggregators/codec_test.go
- aggregators/config.go
- aggregators/converter_test.go
- aggregators/models.go
Updates `CombinedMetricsKey.ID` and the aggregation interfaces to use `[16]byte` instead of `string`. This also fixes the size of binary encoded `CombinedMetricsKey` which will allow us to do efficient pooling for the buffer used to encode `CombinedMetricsKey`.
> Fix size of combined metrics key

- Makefile
- aggregationpb/aggregation_vtproto.pb.go
- aggregationpb/labels_vtproto.pb.go
- aggregators/aggregator.go
- aggregators/aggregator_test.go
- aggregators/codec.go
- aggregators/converter.go
- aggregators/converter_test.go
- aggregators/hasher.go
- aggregators/hasher_test.go
- aggregators/merger_test.go
- aggregators/models.go
- go.mod
- go.sum
Removes the translation layer for calls to `AggregateBatch`.
Before, for every received `APMEvent` we will create a intermediary model which would eventually get translated to the proto model. The proto model would get marshaled to binary representation and indexed in pebble.
After this PR, we directly create the proto model for every received `APMEvent`.
Benchmarking results:
```
name                         old time/op    new time/op    delta
AggregateCombinedMetrics-10    2.79µs ± 2%    3.60µs ± 4%  +29.06%  (p=0.000 n=10+10)
AggregateBatchSerial-10        12.7µs ± 3%     9.1µs ± 2%  -28.38%  (p=0.000 n=10+9)
AggregateBatchParallel-10      14.2µs ± 3%     9.3µs ± 2%  -34.37%  (p=0.000 n=10+9)
CombinedMetricsEncoding-10     3.89µs ± 1%    3.71µs ± 1%   -4.69%  (p=0.000 n=10+10) …
```
> Use proto models directly for AggregateBatch

- aggregators/aggregator.go
This removes the need for exclusive locking to update the cached event stats in `Aggregate*` methods.
The cperformance changes are negligible, which is expected. I think CombinedMetricsEncoding-16 has more variance than the benchstat output lets on -- in another run it was faster than main, but with a wider range.
```
goos: linux
goarch: amd64
cpu: AMD Ryzen 7 PRO 5850U with Radeon Graphics     
│ /tmp/main.txt │            /tmp/pr.txt             │
│    sec/op     │    sec/op     vs base              │
AggregateCombinedMetrics       8.373µ ±  6%   8.262µ ±  2%       ~ (p=0.485 n=6)
AggregateCombinedMetrics-8     6.322µ ± 11%   6.393µ ± 10%       ~ (p=0.699 n=6)
AggregateCombinedMetrics-16    6.610µ ±  9%   6.338µ ± 10%       ~ (p=0.937 …
```
> Switch to sync.Map for cached event stats

- aggregationpb/hash.go
- aggregators/codec.go
- aggregators/converter.go
- aggregators/hasher.go
- aggregators/models.go
- aggregators/nullable/bool.go
- aggregators/nullable/doc.go
benchstat:
```
goos: linux
goarch: amd64
│ bench-out/hashable-func-alloc-before │ bench-out/hashable-func-alloc-after │
│                sec/op                │   sec/op     vs base                │
AggregateCombinedMetrics-16                            4.003µ ± 3%   4.072µ ± 2%        ~ (p=0.342 n=10)
AggregateBatchSerial-16                                10.46µ ± 3%   10.26µ ± 4%        ~ (p=0.645 n=10)
AggregateBatchParallel-16                              11.07µ ± 5%   10.73µ ± 5%        ~ (p=0.190 n=10)
CombinedMetricsEncoding-16                             4.842µ ± 2%   4.829µ ± 3%        ~ (p=0.869 n=10)
CombinedMetricsDecoding-16                             4.449µ ± 2%   4.494µ …
```
> Avoid alloc on creating hashable func

- aggregators/converter.go
benchstat:
```
goos: linux
goarch: amd64
│ bench-out/converter-nil-slices-before │ bench-out/converter-nil-slices-after │
│                sec/op                 │    sec/op      vs base               │
AggregateCombinedMetrics-16                            4.076µ ± 36%     4.056µ ± 2%       ~ (p=0.516 n=10)
AggregateBatchSerial-16                                10.32µ ±  2%     10.09µ ± 3%       ~ (p=0.123 n=10)
AggregateBatchParallel-16                              10.94µ ± 14%     10.60µ ± 5%       ~ (p=0.393 n=10)
CombinedMetricsEncoding-16                             5.144µ ±  4%     4.999µ ± 2%  -2.82% (p=0.027 n=10)
CombinedMetricsDecoding-16                             4.494µ ± …
```
> Nil out the slices to reduce alloc

- aggregators/aggregator.go
- aggregators/aggregator_test.go
- aggregators/codec.go
- aggregators/codec_test.go
- aggregators/combined_metrics_test.go
- aggregators/converter.go
- aggregators/converter_test.go
- aggregators/merger.go
- aggregators/merger_test.go
- aggregators/models.go
Optimizes merging of metrics by optimizing translation to proto models.
Benchmark with main:
```
name                         old time/op    new time/op    delta
AggregateCombinedMetrics-10    3.52µs ± 2%    1.69µs ± 2%  -51.96%  (p=0.000 n=8+10)
AggregateBatchSerial-10        8.71µs ± 2%    5.40µs ± 3%  -37.98%  (p=0.000 n=10+10)
AggregateBatchParallel-10      8.89µs ± 2%    5.74µs ± 1%  -35.38%  (p=0.000 n=10+9)
CombinedMetricsEncoding-10     3.63µs ± 1%    0.98µs ± 0%  -72.93%  (p=0.000 n=10+8)
CombinedMetricsDecoding-10     4.43µs ± 1%    0.38µs ± 0%  -91.40%  (p=0.000 n=10+10)
CombinedMetricsToBatch-10       354µs ± 0%     206µs ± 1%  -41.76%  (p=0.000 n=10+10)
EventToCombinedMetrics-10       599ns ± 1%     598ns ± 0%     ~     (p=0.151 n=8+10)
name                         old …
```
> Optimize proto translation for merger

- aggregators/aggregator.go
- aggregators/aggregator_test.go
- aggregators/cachedeventsmap.go
This changes the semantics slightly: Close should always be called, whereas Stop suggests that it should be paired with Run. Close closes the underlying database, and ensures any running harvester is stopped. This removes the need for flushTestAggregator in the tests.
Also, move cachedEventsMap to its own file.
> Replace Aggregator.Stop with Aggregator.Close

- aggregators/aggregator.go
- aggregators/aggregator_test.go
- aggregators/codec.go
- aggregators/codec_test.go
- aggregators/combined_metrics_test.go
- aggregators/converter.go
- aggregators/converter_test.go
- aggregators/merger.go
- aggregators/merger_test.go
- aggregators/models.go
Removes `FromProto` methods for all `*Metrics` struct.
Hides all non-proto structs as private structs other than `CombinedMetricsKey` and `GlobalLabels`
Follow up of #40
> Remove FromProto and hide most non-proto structs

- aggregators/converter.go
- aggregators/merger.go
It is possible for vtproto pool to have estimator bytes as a non-nil slice of length zero. To check if overflow exists, check for the length of the estimator bytes to be `0`.
> Check length of binary estimator to find overflow

- aggregators/converter.go
- aggregators/converter_test.go
- aggregators/internal/hdrhistogram/hdrhistogram.go
- go.mod
- go.sum
Dependent on https://github.com/elastic/apm-data/pull/128
Benchmarking:
```
name                       old time/op    new time/op    delta
CombinedMetricsToBatch-10     202µs ± 0%     200µs ± 1%   -0.86%  (p=0.000 n=10+10)
name                       old alloc/op   new alloc/op   delta
CombinedMetricsToBatch-10    38.6kB ± 0%     4.2kB ± 0%  -89.15%  (p=0.000 n=8+9)
name                       old allocs/op  new allocs/op  delta
CombinedMetricsToBatch-10       308 ± 0%        95 ± 0%  -69.16%  (p=0.000 n=10+10)
```
Small gain in terms of `time/op`. For `time/op` it seems a lot of time is spent on `HDRHistogramRepresentation#Buckets`. I think it can be optimized for sparse representations, I have added a TODO.
> Pool events for final processing of combined metrics

- aggregators/codec.go
- aggregators/converter.go
- go.mod
Create pooled "metrics builder" objects, which contain enough space to produce metrics for a single event, and use interior pointers within the object to reduce allocations and the need for allocating/freeing/pooling many small objects.
```
goos: linux
goarch: amd64
cpu: AMD Ryzen 7 PRO 5850U with Radeon Graphics     
│ /tmp/main.txt │             /tmp/pr.txt             │
│    sec/op     │    sec/op     vs base               │
AggregateCombinedMetrics-16    2.904µ ±  8%   3.010µ ± 14%        ~ (p=0.485 n=6)
AggregateBatchSerial-16        9.913µ ±  7%   9.293µ ± 10%        ~ (p=0.065 n=6)
AggregateBatchParallel-16     12.715µ ± 13%   9.864µ ±  3%  -22.42% (p=0.002 n=6)
CombinedMetricsEncoding-16     1.422µ ±  4%   1.401µ ±  7%        ~ …
```
> Reduce fragmentation in EventToCombinedMetrics

- aggregators/combined_metrics_test.go
- aggregators/converter.go
- aggregators/converter_test.go
Transaction and service transaction needs to be reset. One case which presents an issue is `ServiceTransactionMetrics#SuccessCount` and `ServiceTransactionMetrics#FailureCount` which are not reset.
> Reset service txn and txn metrics

- aggregators/aggregator.go
- aggregators/config.go
- aggregators/converter.go
- aggregators/converter_test.go
Configure a number of partitions, and always just calculate the partition has `hash%partitions`. The existing API is more or less required to do this anyway, since it receives a hash.
I'm intending to move the `EventToCombinedMetrics` function and related code to a separate internal package, and this will simplify that.
> Remove Partitioner interface

- aggregationpb/aggregation_vtproto.pb.go
- aggregationpb/labels_vtproto.pb.go
- aggregators/codec.go
- aggregators/merger.go
- tools/go.mod
- tools/go.sum
Alternative to #37 , but using vtprotobuf fork that reuses backing array including referenced structs, which has an upstream PR. With this, we will no longer be pooling Keyed* individually. Either with this or #37, there will be significantly fewer garbage.
Closes #20
benchstat:
```
goos: linux
goarch: amd64
│ bench-out/vt-unmarshal-pooling-including-structs-2-before │ bench-out/vt-unmarshal-pooling-including-structs-2-after │
│                          sec/op                           │              sec/op                vs base               │
AggregateCombinedMetrics-16                                                            2.001µ ± 1%                         1.926µ ± 1%   -3.75% …
```
> vtprotobuf: Reuse backing array with referenced structs instead of pooling individual objects

- aggregators/merger.go
- aggregators/merger_test.go
Optimize mergeHistogram for single value in `from` histogram, since it will be the majority case.
Alternative to #66. 
Also attached benchstat of BenchmarkMergeHistogram. It is a microbenchmark that measures time to merge single value `from` histogram to `to` histogram of size `size` and whether that the single value already exists in `to.Buckets`. It is not super well written and possibly only useful for this time. Therefore I've not included it in the change, but only attaching it in this PR description.
benchstat:
```
goos: linux
goarch: amd64
│ bench-out/merge-histogram-fastpath-8-before │ bench-out/merge-histogram-fastpath-8-after │
│                   sec/op                    │ …
```
> perf: Add mergeHistogram fast path for single value from

- aggregators/converter.go
Prior to this PR, the code was not accounting for metrics added due to global overflow for txn, service txn, and span metric during size estimation for the batch before converting the harvested `CombinedMetrics` to batch of `APMEvent`s.
> Fix incorrect size estimation on global overflow

- aggregators/aggregator.go
- aggregators/aggregator_test.go
- aggregators/codec.go
- aggregators/codec_test.go
Adds a constant `CombinedMetricsKeyEncodedSize` to represent the size of encoded combined metrics key. This can be used to prevent allocations caused by `make` for `CombinedMetricsKey` decoding/encoding. Since it is an exposed value, if in future we move to variable length encoded combined metrics key that would result in a breaking change however, I don't think that should happen.
Adds a util method `GetEncodedCombinedMetricsKeyWithoutPartitionID` to strip an encoded combined metrics key of its partition. Added it here since it will be easy to maintain here if the logic changes in future.
> Add method to get combined metrics key without partition

- aggregators/aggregator_test.go
- aggregators/converter.go
- aggregators/converter_test.go
Before this PR, we didn't emit service summary metric in following cases:
1. When the representative count for input transaction/span is zero
2. When span event is not an exit span
With this PR, we emit service summary metric for all events.
> Emit service summary metric for all events

- aggregators/aggregator_test.go
- aggregators/converter.go
- aggregators/converter_test.go
- go.mod
- go.sum
Update to uint64-based durations -- https://github.com/elastic/apm-data/pull/142
> Update apm-data for uint64 event duration

- aggregators/aggregator.go
- aggregators/aggregator_test.go
- aggregators/config.go
Overflow logging is important for insight into aggregations and diagnosing high cardinality dimensions. This was in apm-server and we should retain this feature in apm-aggregation. Aggregator now accepts an optional logging function that will be called when overflow is present during harvest. Log messages will look similar to apm-server aggregation overflow log messages. As overflow can happen due to global limit or per-service limit breach, add additional logic in order to output meaningful and actionable logs.
Part of #75
> Add logging for overflow

- aggregators/aggregator_test.go
- aggregators/converter.go
- aggregators/converter_test.go
Sets `event.received` to the youngest `event.received` from the aggregated batch for all aggregated metrics including overflows.
Closes #91
> Set received timestamp for aggregated metrics

- aggregators/aggregator_test.go
- aggregators/converter.go
- aggregators/converter_test.go
Changes the approach adopted in https://github.com/elastic/apm-aggregation/pull/92 to use youngest event timestamp as `event.received`. Now, we directly use `time.Now()` when converting combined metrics to APM events.
> Use converted timestamp as event.received

- aggregators/aggregator.go
- aggregators/aggregator_test.go
- aggregators/combined_metrics_test.go
- aggregators/config.go
- aggregators/config_test.go
Introduce max lookback period which configures the maximum duration that the aggregator will use to query the database during harvest time in addition to the original period derived from aggregation interval i.e. the harvest interval for each aggregation interval will be defined as `[end-MaxLookback-AggregationIvl, end)`.
The main purpose of `MaxLookback` is to protect against data loss for multi level deployments of aggregators where AggregateCombinedMetrics is used to aggregate partial aggregates. In these cases, the MaxLookback configuration can protect against data loss due to delayed partial aggregates (see test case). Note that these delayed partial aggregates will only be aggregated with other delayed partial aggregates and thus we can have multiple aggregated metrics for
the same …
> Introduce max lookback period

- aggregators/aggregator.go
- aggregators/codec.go
- aggregators/codec_test.go
- aggregators/config.go
- aggregators/config_test.go
- aggregators/converter.go
- aggregators/converter_test.go
- aggregators/models.go
This is an attempt to reduce the size of the public API in the `aggregators` package, as a first step towards making it easier to grasp.
It:
* Makes the config private. We don't need to access the config struct, we pass config as functional parameters.
* Makes `GlobalLabels` private. This struct is only used within that package.
* Makes `EventToCombinedMetrics` private, as it's also only used within that package.
> Reduce public api

- aggregators/aggregator.go
- aggregators/aggregator_test.go
Discards events that are too old to be harvested before aggregation. Prior to this PR, such events would stay in pebble and would impact our SLOs without any error logs.
> Discard too old events before processing

- aggregators/aggregator.go
Uses the more performant `metric.WithAttributeSet` everywhere.
> metrics: Use `metric.WithAttributeSet` everywhere

- .github/workflows/ci.yml
In the current configuration the workflow runs twice in a PR, because it runs for the `pull_request` event and for the `push` event on the branch. 
This way, it will only be triggered for pushes to the `main` branch and on `pull_request` events.
> ci: don't run workflow twice in a PR

- .github/workflows/add-to-project.yaml
No more finer-grained tokens but ephemeral tokens using a GH app
> github-actions: use ephemeral tokens

- aggregators/aggregator.go
- aggregators/converter.go
- aggregators/converter_test.go
- aggregators/merger.go
This PR exposes `EventToCombinedMetrics` and `MergeCombinedMetrics` internal functionality as a part of public API. This is useful for testing purposes and allows to easily implement simple aggregation logic in memory bypassing badger.
> testing: expose convert and merge as public
